#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
set -x
if [ ! -d $OPENSHIFT_DATA_DIR/jdk1.8.0_20 ]
  then
    cd $OPENSHIFT_DATA_DIR
    wget http://www.java.net/download/jdk8u20/archive/b17/binaries/jdk-8u20-ea-bin-b17-linux-x64-04_jun_2014.tar.gz
    tar xvf *.tar.gz
    rm -f *.tar.gz
fi

if [ ! -d $OPENSHIFT_DATA_DIR/suadeome ]
then
  mkdir -p $OPENSHIFT_DATA_DIR/suadeome
fi

if [ ! -d $OPENSHIFT_DATA_DIR/gradle-3.3 ]
  then
    cd $OPENSHIFT_DATA_DIR
    wget https://services.gradle.org/distributions/gradle-3.3-bin.zip
    unzip gradle-3.3-bin.zip
    rm -f gradle-3.3-bin.zip
fi

export GRADLE_USER_HOME=$OPENSHIFT_DATA_DIR/gradle
export GRADLE_HOME=$OPENSHIFT_DATA_DIR/gradle-3.3

export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_20
export PATH=$JAVA_HOME/bin:$GRADLE_HOME:$PATH

cd $OPENSHIFT_REPO_DIR
gradle clean uberjar
cp build/libs/*.jar $OPENSHIFT_DATA_DIR/suadeome
